# Generated by Django 3.0.7 on 2020-06-26 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=10, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('qualification', models.CharField(blank=True, choices=[('phd', 'PhD'), ('msc', 'Masters'), ('deg', 'Degree'), ('hnd', 'HND'), ('nce', 'NCE'), ('diploma', 'Diploma'), ('ssce', 'SSCE'), ('pri', 'Primary'), ('others', 'Others')], default='', max_length=10, null=True)),
                ('designation', models.CharField(blank=True, choices=[('chm', 'Chairman'), ('vchm', 'Vice Chairman'), ('sec', 'Secretary'), ('fsec', 'Financial Secretary'), ('asec', 'Assistant Secretary'), ('tre', 'Treasurer'), ('osec', 'Organising Secretary'), ('aosec', 'Assistant Organising Secretary'), ('legal', 'Legal Adviser'), ('aud1', 'Auditor I'), ('aud2', 'Auditor II'), ('pro1', 'PRO I'), ('pro2', 'PRO II'), ('ylead', 'Youth Leader'), ('wlead', 'Women Leader'), ('dcoord', 'District Coordinator'), ('mem', 'Member')], default='mem', max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=6, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
                ('state', models.CharField(blank=True, choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwaibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cr', 'Cross River'), ('belta', 'Delta'), ('edo', 'Edo'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('tlateau', 'Plateau'), ('Rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('Yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT')], default='Bauchi', max_length=20, null=True)),
                ('senatorial_district', models.CharField(blank=True, choices=[('Bauchi South', 'Bauchi South'), ('Bauchi Central', 'Bauchi Central'), ('Bauchi North', 'Bauchi North')], default='', max_length=20, null=True)),
                ('local_government', models.CharField(blank=True, choices=[('Alkaleri', 'Alkaleri'), ('Bauchi', 'Bauchi'), ('Bogoro', 'Bogoro'), ('Dambam', 'Dambam'), ('Darazo', 'Darazo'), ('Dass', 'Dass'), ('Gamawa', 'Gamawa'), ('Ganjuwa', 'Ganjuwa'), ('Giade', 'Giade'), ('Itas gadau', 'Itas gadau'), ('Jamaare', 'Jamaare'), ('Katagum', 'Katagum'), ('Kirfi', 'Kirfi'), ('Misau', 'Misau'), ('Ningi', 'Ningi'), ('Shira', 'Shira'), ('Tafawa Balewa', 'Tafawa Balewa'), ('Toro', 'Toro'), ('Warji', 'Warji'), ('Zaki', 'Zaki')], default='Toro', max_length=20, null=True)),
                ('district', models.CharField(blank=True, choices=[('Jamaa', "Jama'a District"), ('Toro District', 'Toro District'), ('Lame District', 'Lame District')], default='', max_length=20, null=True)),
                ('ward', models.CharField(blank=True, choices=[('Toro', 'Toro'), ('Tilde', 'Tilde'), ('Ribina West', 'Ribina West'), ('Ribina East', 'Ribina East'), ('Tulai', 'Tulai'), ('Mara', 'Mara'), ('Palama', 'Palama'), ('Jamaa', "Jama'a"), ('Zaranda', 'Zaranda'), ('Rauta geji', 'Rauta geji'), ('Wonu South', 'Wonu South'), ('Wonu North', 'Wonu North'), ('Rishi', 'Rishi'), ('Zalau', 'Zalau'), ('Rahama', 'Rahama'), ('Tama', 'Tama'), ('Lame', 'Lame')], default='', max_length=20, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('house_no', models.CharField(max_length=30)),
                ('about', models.TextField(blank=True, help_text='Write a little about yourself', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
