# Generated by Django 3.0.7 on 2020-06-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/pictures/')),
                ('project_leader', models.CharField(max_length=50)),
                ('estimated_duration', models.PositiveSmallIntegerField(default=0, help_text='Number in weeks')),
                ('estimated_budget', models.FloatField()),
                ('total_amount_spent', models.FloatField()),
                ('about_project', models.TextField()),
                ('beneficiaries', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='blog.Category')),
                ('next_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='portfolio.Project')),
                ('previous_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='portfolio.Project')),
                ('sponsors', models.ManyToManyField(to='partner.Partner')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
