# Generated by Django 3.0.7 on 2020-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50, verbose_name='LGA')),
                ('status', models.CharField(choices=[('gov', 'Governmental'), ('ngo', 'Non-Governmental'), ('pro', 'Profit'), ('npro', 'Non-Profit'), ('ind', 'Individual')], default='ngo', max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='partner/logo/')),
                ('about', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
